version: "3.7"
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.10.22.0/16

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      profile: prod
    ports:
      - 8080:8080
    networks:
      mynetwork:
        ipv4_address:
          172.10.22.3
  db:
    image: mysql
    container_name: db
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=todolist"
    ports:
      - 3306:3306
    networks:
      mynetwork:
        ipv4_address:
          172.10.22.2
